# Generated by Django 5.1.4 on 2024-12-11 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_aifeedback_options_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
