# Generated by Django 5.1.4 on 2024-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_document_author_alter_document_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
